---
name: Amazon Linux @ AArch64
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/amazon-aarch64.yml'
jobs:
  amazon:
    env:
      dist: 'amazon'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '2' ]
        tarantool-version: [ '2.10' ]
        build: [ 'script', 'manual' ]
    runs-on: [ self-hosted, graviton ]
    steps:
      - uses: actions/checkout@master

      - uses: tarantool/actions/setup-venv@lastochka42/fix-setup-venc-condition

      - uses: ./.github/actions/check
        with:
          dist: ${{ env.dist }}
          dist-version: ${{ matrix.dist-version }}
          tarantool-version: ${{ matrix.tarantool-version }}
          build: ${{ matrix.build }}
