name: Amazon Linux
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/amazon.yml'

# Cancel workflow runs on PRs when the PR is updated with a newer commit.
# Such runs will have a concurrency group named
# `{github.workflow}-{github.ref}`,
# for example,
# `Amazon Linux-refs/pull/42/merge`.
#
# Runs on branch `master` and tags will never be canceled,
# due to having a unique group name
# `{github.run_id}-{github.run_attempt}`,
# for example,
# `3477882280-1`.
concurrency:
  group: ${{
    (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')
    ) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  amazon:
    env:
      dist: 'amazon'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '2' ]
        tarantool-version: [ '2.10', '1.10' ]
        build: [ 'script' ]
    runs-on: [ self-hosted, ubuntu-20.04-self-hosted ]
    steps:
      - uses: actions/checkout@master

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.5'
          cache: pip
      - name: Setup Python requirements
        run: pip install -r requirements.txt

      - name: Check installation of Tarantool
        run: |
          python check.py --config config-example.json \
            --dist ${{ env.dist }} \
            --dist-version ${{ matrix.dist-version }} \
            --version ${{ matrix.tarantool-version }} \
            --build ${{ matrix.build }} \
            -d -v
