---
name: RHEL/CentOS @ AArch64
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/centos-aarch64.yml'

# Cancel workflow runs on PRs when the PR is updated with a newer commit.
# Such runs will have a concurrency group named
# `{github.workflow}-{github.ref}`,
# for example,
# `Amazon Linux-refs/pull/42/merge`.
#
# Runs on branch `master` and tags will never be canceled,
# due to having a unique group name
# `{github.run_id}-{github.run_attempt}`,
# for example,
# `3477882280-1`.
concurrency:
  group: ${{
    (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')
    ) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  centos-aarch64:
    env:
      dist: 'centos'

    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '8', '7' ]
        tarantool-version: [ '2.11.4' ]
        build: [ 'script', 'manual' ]
        include:
          - dist-version: '8'
            tarantool-version: '3.1.1'
            build: 'script'

    runs-on: [ self-hosted, graviton ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Change Docker image if needed
        run: |
          version="${{ matrix.dist-version }}"
          if ${{ contains('7', matrix.dist-version) }}; then
            version="tarantool/delivery-checker:centos-${{ matrix.dist-version }}"
          fi
          echo "version=${version}" >> $GITHUB_ENV

      - name: Check installation of Tarantool
        uses: ./.github/actions/check
        with:
          dist: ${{ env.dist }}
          dist-version: ${{ env.version }}
          tarantool-version: ${{ matrix.tarantool-version }}
          build: ${{ matrix.build }}

      - name: Send notification on failure
        if: failure()
        uses: ./.github/actions/failure-notify
        with:
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          service-chat-id: ${{ secrets.VKTEAMS_SERVICE_CHAT_ID }}
          debug-chat-id: ${{ secrets.VKTEAMS_DEBUG_CHAT_ID }}
