name: Check
on:
  workflow_dispatch:
jobs:
  run_check:
    runs-on: self-hosted
    steps:
      - name: Run delivery checker
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd ${{ secrets.REMOTE_PATH }}
            export PATH="${PATH}:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
            ./run_check.sh
