---
name: Debian @ AArch64
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/debian-aarch64.yml'

# Cancel workflow runs on PRs when the PR is updated with a newer commit.
# Such runs will have a concurrency group named
# `{github.workflow}-{github.ref}`,
# for example,
# `Amazon Linux-refs/pull/42/merge`.
#
# Runs on branch `master` and tags will never be canceled,
# due to having a unique group name
# `{github.run_id}-{github.run_attempt}`,
# for example,
# `3477882280-1`.
concurrency:
  group: ${{
    (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')
    ) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  debian:
    env:
      dist: 'debian'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '11', '10' ]
        tarantool-version: [ '2.10' ]
        build: [ 'script', 'manual' ]
    runs-on: [ self-hosted, graviton ]
    steps:
      - uses: actions/checkout@master

      - uses: tarantool/actions/setup-venv@master

      - uses: ./.github/actions/check
        with:
          dist: ${{ env.dist }}
          dist-version: ${{ matrix.dist-version }}
          tarantool-version: ${{ matrix.tarantool-version }}
          build: ${{ matrix.build }}
