name: Debian @ AArch64
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/debian-aarch64.yml'
jobs:
  debian:
    env:
      dist: 'debian'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '11']
        tarantool-version: [ '2.10' ]
        build: [ 'script' ]
    runs-on: [ self-hosted, graviton ]
    steps:
      - uses: actions/checkout@master

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
          cache: pip
      - name: Setup Python requirements
        run: pip install -r requirements.txt

      - name: Check installation of Tarantool
        run: |
          python check.py --config config-example.json \
            --dist ${{ env.dist }} \
            --dist-version ${{ matrix.dist-version }} \
            --version ${{ matrix.tarantool-version }} \
            --build ${{ matrix.build }} \
            -d -v
