name: Fedora
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/fedora.yml'
jobs:
  fedora:
    env:
      dist: 'fedora'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '36', '35', '34' ]
        tarantool-version: [ '2.10', '1.10' ]
        build: [ 'script', 'manual' ]
        exclude:
          - tarantool-version: '1.10'
            dist-version: '36'
    runs-on: [ self-hosted, ubuntu-20.04-self-hosted ]
    steps:
      - uses: actions/checkout@master

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.5'
          cache: pip
      - name: Setup Python requirements
        run: pip install -r requirements.txt

      - name: Check installation of Tarantool
        run: |
          python check.py --config config-example.json \
            --dist ${{ env.dist }} \
            --dist-version ${{ matrix.dist-version }} \
            --version ${{ matrix.tarantool-version }} \
            --build ${{ matrix.build }} \
            -d -v
