name: OpenSUSE
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/opensuse.yml'
jobs:
  opensuse:
    env:
      dist: 'opensuse'
    strategy:
      fail-fast: false
      matrix:
        dist-version: [ "15.2", "15.1" ]
        tarantool-version: [ '2.8', '1.10' ]
        build: [ 'script', 'manual' ]
    runs-on: [ self-hosted, ubuntu-20.04-self-hosted ]
    steps:
      - uses: actions/checkout@master

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.5'
          cache: pip
      - name: Setup Python requirements
        run: pip install -r requirements.txt

      - name: Check installation of Tarantool
        run: |
          python check.py --config config-example.json \
            --dist ${{ env.dist }} \
            --dist-version ${{ matrix.dist-version }} \
            --version ${{ matrix.tarantool-version }} \
            --build ${{ matrix.build }} \
            -d -v
