name: macOS
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/osx.yml'

# Cancel workflow runs on PRs when the PR is updated with a newer commit.
# Such runs will have a concurrency group named
# `{github.workflow}-{github.ref}`,
# for example,
# `Amazon Linux-refs/pull/42/merge`.
#
# Runs on branch `master` and tags will never be canceled,
# due to having a unique group name
# `{github.run_id}-{github.run_attempt}`,
# for example,
# `3477882280-1`.
concurrency:
  group: ${{
    (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')
    ) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  osx:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-12', 'macos-13' ]
        tarantool-version: [ '3.2.0' ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.5'
          cache: pip

      - name: Setup Python requirements
        run: pip install -r requirements.txt

      - name: Fetch newest version of Homebrew and all formulae
        run: brew update --auto-update

      - name: Check installation of Tarantool
        run: |
          python check.py --host-mode \
            --version ${{ matrix.tarantool-version }} \
            --build brew \
            -d -v

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ github.job }}-${{ Join(matrix.*, '-') }}
          path: archive

      - name: Send notification
        if: failure()
        uses: ./.github/actions/failure-notify
        with:
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          service-chat-id: ${{ secrets.VKTEAMS_SERVICE_CHAT_ID }}
          debug-chat-id: ${{ secrets.VKTEAMS_DEBUG_CHAT_ID }}
