name: Running
on:
  workflow_dispatch:
jobs:
  running:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Run delivery checker
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd ${{ secrets.REMOTE_PATH }}
            ./run_check.sh
            export EXIT_CODE=$?
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} local
            exit $EXIT_CODE
