name: Running
on:
  workflow_dispatch:
jobs:
  running:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Run delivery checker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 360m
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            source venv/bin/activate
            python3 check.py
            export EXIT_CODE=$?
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} local
            exit $EXIT_CODE
