---
name: Ubuntu @ AArch64
on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ubuntu-aarch64.yml'

# Cancel workflow runs on PRs when the PR is updated with a newer commit.
# Such runs will have a concurrency group named
# `{github.workflow}-{github.ref}`,
# for example,
# `Amazon Linux-refs/pull/42/merge`.
#
# Runs on branch `master` and tags will never be canceled,
# due to having a unique group name
# `{github.run_id}-{github.run_attempt}`,
# for example,
# `3477882280-1`.
concurrency:
  group: ${{
    (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')
    ) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  ubuntu-aarch64:
    env:
      dist: 'ubuntu'

    strategy:
      fail-fast: false
      matrix:
        dist-version: [ '22.04', '20.04' ]
        tarantool-version: [ '2.11']
        build: [ 'script', 'manual' ]

    runs-on: [ self-hosted, graviton ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check installation of Tarantool
        uses: ./.github/actions/check
        with:
          dist: ${{ env.dist }}
          dist-version: ${{ matrix.dist-version }}
          tarantool-version: ${{ matrix.tarantool-version }}
          build: ${{ matrix.build }}

      - name: Send notification on failure
        if: failure()
        uses: ./.github/actions/failure-notify
        with:
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          service-chat-id: ${{ secrets.VKTEAMS_SERVICE_CHAT_ID }}
          debug-chat-id: ${{ secrets.VKTEAMS_DEBUG_CHAT_ID }}
